// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwyyHrpwvSaav-n9EsxZYtaG66Fe8afE',
    appId: '1:635607471955:web:148775266e9f9379afb3a6',
    messagingSenderId: '635607471955',
    projectId: 'mad2-finalproject',
    authDomain: 'mad2-finalproject.firebaseapp.com',
    storageBucket: 'mad2-finalproject.firebasestorage.app',
    measurementId: 'G-YHVT7SLCC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLsII6tYRsy1l3Ys0dM1p-wEZxmWT754',
    appId: '1:635607471955:android:c9f984713c97da63afb3a6',
    messagingSenderId: '635607471955',
    projectId: 'mad2-finalproject',
    storageBucket: 'mad2-finalproject.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpwyyHrpwvSaav-n9EsxZYtaG66Fe8afE',
    appId: '1:635607471955:web:55d1a9d85c537399afb3a6',
    messagingSenderId: '635607471955',
    projectId: 'mad2-finalproject',
    authDomain: 'mad2-finalproject.firebaseapp.com',
    storageBucket: 'mad2-finalproject.firebasestorage.app',
    measurementId: 'G-PZZ570TSN5',
  );
}
